apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 80        # Port exposed by the service
      targetPort: 5000 # Port on the container
  type: LoadBalancer
