apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask
          image: <your-docker-image>  # Replace with your Docker image
          ports:
            - containerPort: 5000
          env:
            - name: WELCOME_MSG
              valueFrom:
                configMapKeyRef:
                  name: flask-configmap
                  key: welcome-msg
